export const tagsVector = {
	'Indian Case Competition': '/assets/svg/tags/Competition-01.svg',
	'Case Competition': '/assets/svg/tags/Competition-01.svg',
	'International Case Competition': '/assets/svg/tags/Competition-01.svg',
	'Competition': '/assets/svg/tags/Competition-01.svg',
	'MUN': '/assets/svg/tags/Competition-01.svg',
	'Indian Conferences/Summit/Forum': '/assets/svg/tags/Conference-01.svg',
	'Summits/Conferences/Forum': '/assets/svg/tags/Conference-01.svg',
	'International Conferences/Summit/Forum': '/assets/svg/tags/Conference-01.svg',
	'Conference': '/assets/svg/tags/Conference-01.svg',
	'Research Internship': '/assets/svg/tags/Internship-01.svg',
	'Summer Internship': '/assets/svg/tags/Internship-01.svg',
	'Internship': '/assets/svg/tags/Internship-01.svg',
	'Scholarship': '/assets/svg/tags/Scholarship-01.svg',
	'Fellowship': '/assets/svg/tags/Scholarship-01.svg',
	'Training Program': '/assets/svg/tags/Workshop-01.svg',
	'Workshop': '/assets/svg/tags/Workshop-01.svg',
	'Accelerator': '/assets/svg/tags/Workshop-01.svg',
	'Bootcamp': '/assets/svg/tags/Workshop-01.svg',
	'Incubator': '/assets/svg/tags/Workshop-01.svg',
	'Volunteering': '/assets/svg/tags/Workshop-01.svg',
	'Policy Bootcamp': '/assets/svg/tags/Workshop-01.svg',
	'Community': '/assets/svg/tags/Workshop-01.svg',
	'Immersion Program': '/assets/svg/tags/Workshop-01.svg',
	'International Summer School': '/assets/svg/tags/Courses-01.svg',
	'Summer School': '/assets/svg/tags/Courses-01.svg',
	'Winter School': '/assets/svg/tags/Courses-01.svg',
	'Course': '/assets/svg/tags/Courses-01.svg',
	'MOOC': '/assets/svg/tags/Courses-01.svg',
	'Coding Competition': '/assets/svg/tags/Coding-01.svg',
	'Hackathon': '/assets/svg/tags/Coding-01.svg',
	'Coding Platform': '/assets/svg/tags/Coding-01.svg',
	'Game development Competition': '/assets/svg/tags/Coding-01.svg',
	'App Development Competition': '/assets/svg/tags/Coding-01.svg',
	'Algorithmic Trading': '/assets/svg/tags/Finance1-01.svg',
	'Quantitative Finance': '/assets/svg/tags/Finance1-01.svg',
	'Econometrics': '/assets/svg/tags/Finance1-01.svg',
	'Financial Modelling': '/assets/svg/tags/Finance1-01.svg',
	'Research': '/assets/svg/tags/Finance1-01.svg',
	'Data Science': '/assets/svg/tags/Finance1-01.svg',
	'Economics': '/assets/svg/tags/Finance2-01.svg',
	'Investment Banking': '/assets/svg/tags/Finance2-01.svg',
	'Corporate Finance': '/assets/svg/tags/Finance2-01.svg',
	'Business Valuation': '/assets/svg/tags/Finance2-01.svg',
	'Banking': '/assets/svg/tags/Finance2-01.svg',
	'Asset Management': '/assets/svg/tags/Finance2-01.svg',
	'Financial Management': '/assets/svg/tags/Finance2-01.svg',
}